version: '3.4'

services:
  microerp.api:
    image: ${DOCKER_REGISTRY-}microerpapi        

    build:
      context: .
      dockerfile: MicroERP.API/Dockerfile
    depends_on:
      - sqlserver
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    hostname: 'sqlserver'
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: "dbPass1234"
    volumes:
      - E:/DockerVolumes/mssql:/var/opt/mssql3
    ports:
      - '11433:1433'    
    expose:
      - 1433
